---
apiVersion: v1 
kind: Namespace 
metadata:
  name: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserver
  labels:
    app: codeserver

data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-139.59.217.207.nip.io # kubectl get svc -A to get the IP of the load balancer

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
  labels:
    app: codeserver

data:
  PASSWORD: Y2hhbmdlaXQ= # in terminal --> echo -n "stringName" | base64
  SUDO_PASSWORD: c3VkbyBwYXNzd29yZA==