apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    project: bggapp-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      project: bggapp-deploy
  template:
    metadata:
      labels:
        project: bggapp-deploy
    spec:
      containers:
        - name: bgg-backend
          image: stackupiss/bgg-backend:v2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 60
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    project: bgg
spec:
  type: LoadBalancer # Go to DigitalOcean --> Network
  selector:
    project: bggapp-deploy  # Match the label of the deployment's pods
  ports:
    - name: bggapp-port 
      port: 80 # Service port --> port no. used to access via the load balancer IP
      targetPort: 3000  # Match the container's port

# After deploy, do: "k get no -owide"
