---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: bggns
  labels:
    project: bgg

data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret # Same name across diff resource is ok
  namespace: bggns
  labels:
    project: bgg

data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ= # in terminal --> echo -n "stringName" | base64