# in prod, cannot check this into git repo. Kubernetes has some form of KMS
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
  labels:
    app: minio
type: Opaque
data:
  # need min 8 chars
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ= # in terminal --> echo -n "stringName" | base64